### ISSUE TITLE
Shrodinger's door PBR

### ISSUE THREAD

**Issue by DimetryBadcoder** [xalixilax/xali-s-Enhanced-Vanilla-16x#16]
Hello! 

I have this and AVPBR resource packs, and for some reason PBR on doors works only for certain door placement angles. For example, if door is closed, I can't see the PBR textures, and when it's opened, everything is fine. 

And there is no issue when I disable your pack.

Could you fix it? 

I have Quilt/Sodium setup

**Comment by DimetryBadcoder** [comment]
Nevermind.
I didn't noticed that doors have random textures.
However, I find it kinda weird that they changes when opens :)

**Comment by xalixilax** [comment]
Just to add to this, the issue is the custom blockstates I'm using so the door textures have the proper shadow. To fix this simply delete the blockstates for the doors and everything will work
