### ISSUE TITLE
[Suggestion] Bricks connecting

### ISSUE THREAD

**Issue by TheRealPicasso** [xalixilax/xali-s-Enhanced-Vanilla-16x#24]
Adding those non-working bricks would be cool: https://ibb.co/ygGPWsh

**Comment by xalixilax** [comment]
Could you just describe the issue this link look sketch and adding images to Github is really simple

**Comment by TheRealPicasso** [comment]
> Could you just describe the issue this link look sketch and adding images to Github is really simple

i cant upload images idk why, so i used an image website thats the link, you can check it

**Comment by TheRealPicasso** [comment]
?
